let a = 10;
let fname = "Raj Deep";
let res = true;
//a="Ramesh";
let b = 20;
let fname1 = "Ravi Kumar";
let res1 = true;
let c;
let fname2;
let res2;
c = 200;
fname2 = "Mahesh Kumar";
res2 = true;
let abc = "Abc";
abc = 100;
abc = true;
console.log(fname);
console.log(res);
console.log(a);
